{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "navToMain"
	},
	"PageToOpen": "/zcarcare/Pages/Main.page",
	"BackStackVisible": false,
	"ClearHistory": true,
	"NavigationType": "Outer"
}