{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "odataPayment"
	},
	"OnFailure": {
		"Name": "/zcarcare/Actions/GenericMessageBox.action",
		"Properties": {
			"Message": "Payment failed",
			"Title": "Payment failed",
			"OKCaption": "OK"
		}
	},
	"OnSuccess": {
		"Name": "/zcarcare/Actions/GenericMessageBox.action",
		"Properties": {
			"OnSuccess": "/zcarcare/Actions/navToMain.action",
			"Message": "Payment completed successfully",
			"Title": "Payment",
			"OKCaption": "OK"
		}
	},
	"Target": {
		"Service": "/zcarcare/Services/zcarcare.service",
		"EntitySet": "ZC_OFF_CARCARE",
		"QueryOptions": "/zcarcare/Rules/ReadHeaderQuery.js"
	},
	"Properties": {
		"CashAmount": "#Page:Payment/#Control:FCCash/#Value",
		"CardAmount": "#Page:Payment/#Control:FCCard/#Value",
		"CardAuthCode": "#Page:Payment/#Control:FCAuth/#Value",
		"Currency": "INR"
	}
}