{
	"_Type": "Action.Type.ODataService.CreateRelatedEntity",
	"ActionResult": {
		"_Name": "ODataCreateItem"
	},
	"OnFailure": {
		"Name": "/zcarcare/Actions/GenericMessageBox.action",
		"Properties": {
			"Message": "Create Item Failed",
			"Title": "Create Item",
			"OKCaption": "OK"
		}
	},
	"OnSuccess": "/zcarcare/Actions/CloseModalPage_Complete.action",
	"Target": {
		"Service": "/zcarcare/Services/zcarcare.service",
		"EntitySet": "ZC_OFF_CARITEM"
	},
	"ParentLink": {
		"Target": {
			"EntitySet": "ZC_OFF_CARCARE",
			"QueryOptions": "/zcarcare/Rules/ReadItemQuery.js",
			"ReadLink": "{@odata.readLink}"
		},
		"Property": "_Item"
	}
}