{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "PaymentSuccessMessage"
	},
	"OnSuccess": "/zcarcare/Actions/navToMain.action",
	"Message": "Payment completed successfully",
	"Title": "Payment",
	"OKCaption": "OK"
}